qdrant/haloperidol

- .github/workflows/collect-stats.yaml
- .github/workflows/update-bfb-upload.yaml
- tools/collect-stats.sh
- tools/local/collect-cluster-stats.sh
- tools/local/run-bfb-upload.sh
- tools/run-bfb-upload.sh
- Collect cluster stats in Postgres for Chaos testing
- Migrate to our k8s deployment of chaos-testing repo instead of node on hertzner cloud
> feat: Collect cluster stats in Postgres

- tools/local/collect-stats.sh
Collect snapshot count while collecting other stats.
> feat: Collect snapshot count

- .github/workflows/collect-stats.yaml
Run collect stats cron every 10 minutes instead of 25 minutes past every hour
> feat: Run collect stats cron every 10 minutes

- .github/workflows/collect-stats.yaml
It should run every 15m instead of 10m.
> fix: Collect stats cron should run every 15m

- tools/local/collect-stats.sh
This means it will collect stats even when all the nodes are down.
> fix: Set default values for collect stats cron when node is down

- tools/local/collect-stats.sh
> fix: Handle service unavailable root API response

- tools/check-bfb-health.sh
Wrong table name caused GH action failure
> fix: Table name

- tools/local/run-bfb-upload.sh
> Revert "fix: Collection should use 6 shards with replication factor = 1"

- tools/local/run-bfb-upload.sh
Otherwise, I've seen it failing despite trying 3 times.
> fix: Increase bfb upload delay so data consistency check works smoothly

- tools/check-cluster-health.sh
Find inconsistent points IDs if any
> feat: Find Inconsistent points IDs

- .github/workflows/collect-stats.yaml
- tools/check-cluster-health.sh
This will help with debugging inconsistencies if any.
> feat: Dump collected points as GH action artifact

- tools/check-consistency.py
> fix: Reset first node points on each attempt

- .github/workflows/collect-stats.yaml
- tools/check-cluster-health.sh
This should make it easier/faster to spot issues.
> fix: Highlight failures in cluster health check

- .github/workflows/collect-stats.yaml
- .github/workflows/daily-active-workflow.yaml
- .github/workflows/run-snapshots.yaml
- .github/workflows/update-bfb-search.yaml
- .github/workflows/update-bfb-upload.yaml
This PR aims to  make the actions active even after 60 days . @KShivendu waiting for your feedback !!
> ci: action to  keep the workflow active

- tools/check-consistency.py
Also print node ID when skipping
> fix: Check next node if skipping current node

- tools/local/run-bfb-upload.sh
> feat: Replicate the same shard 3 times using bfb upload

- tools/local/run-bfb-search.sh
- tools/local/run-bfb-upload.sh
This will allow us to restart bfb more frequently without worrying about missing the reason behind crash
> feat: Log bfb output to file with ts

- .github/workflows/update-bfb-search.yaml
- .github/workflows/update-bfb-upload.yaml
This will help us collect more data. BFB crashes are already being logged so we can do this!
> feat: Increase bfb update freq to 1hr

- .github/workflows/update-bfb-search.yaml
- .github/workflows/update-bfb-upload.yaml
Or we might be restarting too early
> feat: BFB should be restarted with 2hr freq

- tools/local/run-bfb-search.sh
- tools/local/run-bfb-upload.sh
Will help with catching any errors
> feat: Add retries to bfb and be verbose with logs

- tools/local/run-collect-stats.sh
This will allow Loki to capture the logs.
> feat: Redirect all output to /var/log

- tools/local/run-collect-stats.sh
> feat: Add timestamp in cron logs

- .github/workflows/run-snapshots.yaml
- tools/local/run-snapshots.sh
- tools/run-snapshots.sh
- tools/run_remote.sh
- Split into parts and log errors
> feat: Improve snapshot cron

- tools/check-consistency.py
Should be useful for debugging and catching unexpected issues.
> feat: Use logfmt in consistency check

- tools/check-consistency.py
Check vector as well as payload.
> feat: Check payload in consistency checks

- tools/check-consistency.py
- tools/local/check-cluster-health.sh
> feat: Run 5 consistency checks in parallel

- tools/local/run-bfb-search.sh
- tools/local/run-bfb-upload.sh
So we can we can use latest features like https://github.com/qdrant/bfb/pull/39
> feat: Use dev branch of bfb

- tools/check-consistency.py
> feat: Count empty payload points

- tools/check-consistency.py
- tools/check-empty-payload.py
- tools/local/run-collect-stats.sh
- Isolate the payload check
- Use `/scroll` instead of `/count` 
- Log point IDs
> fix: Isolate empty payload check

- tools/local/collect-node-metrics.sh
> Log when dead shards are found on a remote peer

- tools/check-consistency.py
> Log response if finding too many peers

- tools/local/collect-node-metrics.sh
Gonna run:
```sql
ALTER TABLE chaos_testing 
ADD COLUMN consensus_status VARCHAR(16);
```
> Collect consensus status for each node

- .github/workflows/collect-stats.yaml
- .github/workflows/run-snapshots.yaml
- .github/workflows/update-bfb-search.yaml
- .github/workflows/update-bfb-upload.yaml
- .github/workflows/update-collect-stats.yaml
- tools/check-cluster-health.sh
- tools/check-consistency.py
- tools/local/check-cluster-health.sh
- tools/local/collect-node-metrics.sh
- tools/local/run-bfb-search.sh
- tools/local/run-bfb-upload.sh
- tools/run-collect-stats.sh
- tools/run-snapshots.sh
Add one more cluster into Chaos Testing.
> Add 3d cluster

- .gitignore
- tools/check-consistency-all-points.py
- tools/check-consistency.py
* Add gitignore
* Only fetch inconsistent ids for node-0 during following attempts (instead of fetching all 200K)
* Handle and log possible json issues on fetching points
> Improve consistency check and add gitignore

- tools/check-consistency-all-points.py
This fixes Loki's behavior in Grafana when the plugin doesn't show any logs, due to too long lines.
> Log only a part of inconsistent points if the amount is too high

- tools/check-consistency-improved.py
- tools/local/check-cluster-health.sh
- tools/local/collect-node-metrics.sh
- tools/local/logging.sh
- tools/local/run-collect-stats.sh
Also disable `trace` level logs that were too verbose.
> Make logging consistent with logfmt and dedicated util functions

- tools/check-consistency-improved.py
- tools/local/check-cluster-health.sh
- tools/local/collect-node-metrics.sh
- tools/local/run-collect-stats.sh
Use new `log` function everywhere and some minor changes like filtering to find at max 200K points when finding missing payload
> Improve logging a bit more
